app/enem10x/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include('home.urls')),
    path('admin/', admin.site.urls),
    path('provas/', include("provas.urls")),
    path('usuarios/', include("usuarios.urls")),
    path('__debug__/', include("debug_toolbar.urls")),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/home/urls.py
from django.urls import path
from home.views import home_view



# App name for refering in other code parts
app_name = 'home'

# Urls 
urlpatterns = [
    path('', home_view, name='home'),

]

app/provas/urls.py
from django.urls import path
from provas.views import (
    prova_choose,
    prova_respondida,
    prova_completa,
    criar_prova_professor,
    get_questoes_by_conteudo_id,
)

# App name for refering in other code parts
app_name = "provas"

# Urls
urlpatterns = [
    path("", prova_choose, name="prova-choose"),
    path("respondida/", prova_respondida, name="prova-respondida"),
    path("completa/<int:prova_id>/", prova_completa, name="prova-completa"),
    path("criar/", criar_prova_professor, name="criar-prova-professor"),
    path(
        "get_provas/<int:conteudo_id>",
        get_questoes_by_conteudo_id,
        name="get_questoes_by_conteudo_id",
    ),
]

app/usuarios/urls.py
from django.urls import path
from usuarios.views import (
    notas_graph,
    signup,
    signupsucess,
    logout_view,
    login_view,
    filter_graph_time,
    platform_view,
    professor_turmas_view,
    criar_turma_view,
    professor_turma_view,
    entra_turma,
    delete_turma,
    aluno_turma_view,
    aluno_turmas_view,
    remover_aluno,
    sair_turma_aluno,
    aluno_provas_feitas,
    user_profile,

)


app_name = "usuarios"

urlpatterns = [
    path("plataforma/", platform_view, name="plataforma"),
    path("plataforma/perfil", user_profile, name="user-profile"),
    path("plataforma/grafico-notas", notas_graph, name="graficos"),
    path("plataforma/filter-graph-time/", filter_graph_time, name="graph-filter"),
    path(
        "plataforma/professor/turmas/", professor_turmas_view, name="professor-turmas"
    ),
    path("plataforma/professor/criar-turma/", criar_turma_view, name="criar-turma"),
    path(
        "plataforma/professor/turma/<int:turma_id>",
        professor_turma_view,
        name="professor-turma",
    ),
    path(
        "plataforma/professor/turma/remover-aluno/<int:turma_id>/<int:aluno_id>",
        remover_aluno,
        name="remover-aluno",
    ),
    path(
        "plataforma/aluno/turma/sair/<int:turma_id>/<int:aluno_id>",
        sair_turma_aluno,
        name="aluno-sair-turma",
    ),
    path("plataforma/aluno/turmas/", aluno_turmas_view, name="aluno-turmas"),
    path("plataforma/aluno/turma/<int:turma_id>", aluno_turma_view, name="aluno-turma"),
    path(
        "plataforma/aluno/provas/", aluno_provas_feitas, name='aluno-provas-feitas'
    ),
    path("plataforma/turma/delete/<int:turma_id>", delete_turma, name="delete-turma"),
    path("plataforma/turma/entrar/", entra_turma, name="entrar-turma"),
    path("login/", login_view, name="login"),
    path("signup/", signup, name="signup"),
    path("conta-criada/", signupsucess, name="signup-sucess"),
    path("logout/", logout_view, name="logout"),
]

app/provas/models.py
from django.db import models

# Create your models here.

    

app/provas/forms.py
from collections.abc import Mapping
from typing import Any
from django import forms
from django.forms.utils import ErrorList
from materiais.models import Materia, Simulado

# Forms down here

class ProvaChoose(forms.Form):
    PROVA_QUESTOES_CHOICE = [(i, str(i)) for i in range(5,46)]
    SIMULADO_QUESTOES_CHOICE = [(30, '30'),(45,'45')]
    def __init__(self, *args, **kwargs) -> None:
        super(ProvaChoose, self).__init__(*args, **kwargs)
        self.fields['materias'].choices = [(materia.id, str(materia)) for materia in (Materia.objects.all())]
        self.fields['simulados'].choices = [(simulado.id, str(simulado)) for simulado in (Simulado.objects.all())]
    num_questoes_prova = forms.ChoiceField(
        choices=PROVA_QUESTOES_CHOICE,
        label='Quantas questoes voce quer de cada materia??',
        widget=forms.Select(),
        required=False
    )
    num_questoes_simulado = forms.ChoiceField(
        choices=SIMULADO_QUESTOES_CHOICE,
        widget=forms.Select(),
        required=False,
    )

    simulados = forms.MultipleChoiceField(
        widget=forms.CheckboxSelectMultiple,
        label='Quais simulados?',
        required=False,
    )
    materias = forms.MultipleChoiceField(
        widget=forms.CheckboxSelectMultiple,
        label='Quais materias?',
        required=False,
    )
    tipo_prova = forms.CharField(
        required=True
    )

app/provas/views.py
from django.shortcuts import render, redirect
from materiais.models import (
    Questao,
    Materia,
    Conteudo,
    ProvaCompleta,
    ProvaRespondida,
    Simulado,
    QuestaoRespondida,
)
from django.contrib import messages
from provas.forms import ProvaChoose
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from django.core.cache import cache
from django.views.decorators.cache import cache_page
from usuarios.decorators import user_has_tag
from django.http import HttpResponse, JsonResponse
from usuarios.models import Aluno
from .funcs_geracao_prova import geracao_simulado, geracao_automatica_lista
from django.urls import reverse


# Create your views here.
@login_required
def prova_choose(request):
    """View responsavel por permitir que o usuario escolha entre simulado e uma lista menor customizavel com escolha de mateiras que ira se adaptar aos conteudos mais errados do individuo."""
    if request.method == "POST":
        choose_prova = ProvaChoose(request.POST)

        if choose_prova.is_valid():
            tipo_prova = choose_prova.cleaned_data["tipo_prova"]
            request.session["tipo_prova"] = tipo_prova
            aluno = request.user.aluno
            if tipo_prova == "materia_escolhida":
                num_questoes = int(choose_prova.cleaned_data["num_questoes_prova"])
                materia_id_list = choose_prova.cleaned_data["materias"]
                if materia_id_list is None:
                    messages.add_message(
                        request,
                        messages.ERROR,
                        f"{request.user.nome} Por favor escolha uma materia!",
                    )
                    return redirect(reverse("provas:prova-choose"))
                questoes, materias = geracao_automatica_lista(
                    materia_id_list, num_questoes
                )

                context = {
                    "questoes": questoes,
                    "materias": materias,
                }
                return render(request, "provas/prova.html", context)

            if tipo_prova == "simulado":
                simulado_id_list = choose_prova.cleaned_data["simulados"]
                num_questoes = int(choose_prova.cleaned_data["num_questoes_simulado"])
                request.session["simulado_id_list"] = simulado_id_list

                if len(simulado_id_list) == 0:
                    messages.add_message(
                        request,
                        messages.ERROR,
                        f"{request.user.nome}, por favor escolha uma matéria!",
                    )
                    return redirect(reverse("provas:prova-choose"))

                questoes, simulados = geracao_simulado(
                    simulado_id_list, num_questoes, aluno
                )

                context = {
                    "questoes": questoes,
                    "simulados": simulados,
                }
                return render(request, "provas/prova.html", context)

    choose_prova = ProvaChoose()
    context = {
        "choose_prova": choose_prova,
    }
    return render(request, "provas/escolha-prova.html", context)


@login_required
@user_has_tag("is_aluno")
def prova_respondida(request):
    if request.method == "POST":
        tipo_prova = request.session.get("tipo_prova")
        aluno = Aluno.objects.get(usuario=request.user)

        if tipo_prova == "materia_escolhida":
            prova_completa = ProvaCompleta.objects.create(aluno=aluno)
            for questao_id, resposta in request.POST.items():
                if "questao_id-" in questao_id:
                    real_questao_id = questao_id.split("-")[1]
                    questao = Questao.objects.get(id=real_questao_id)
                    prova_respondida_obj = ProvaRespondida.objects.create(
                        aluno=aluno,
                        questao=questao,
                        resposta=resposta,
                        prova_completa=prova_completa,
                    )
                    # Define acerto da questao
                    prova_respondida_obj.set_acerto()
            questao_respondida = QuestaoRespondida()
            questao_respondida.set_questoes_ja_respondidas(aluno)
            prova_completa.gera_relatorio()
            # Deleta as questoes respondidas do usuario para nao poluir o banco de dados com informacao inutil.
            prova_completa.deleta_respostas()
            prova_completa_url = reverse(
                "provas:prova-completa", args=[prova_completa.id]
            )
            context = {"prova_completa_url": prova_completa_url}
            cache.delete(f"aluno_provas_feitas_{aluno.id}")
            cache.delete(f"turmas_graph_{aluno.id}")
            return render(request, "provas/prova-respondida.html", context)

        if tipo_prova == "simulado":
            simulado_id_list = request.session.get("simulado_id_list")
            simulados = Simulado.objects.filter(pk__in=simulado_id_list)
            for simulado in simulados:
                prova_completa = ProvaCompleta.objects.create(
                    aluno=aluno, simulado=simulado
                )
                for questao_id, resposta in request.POST.items():
                    if "questao_id-" in questao_id:
                        real_questao_id = questao_id.split("-")[1]
                        questao = Questao.objects.get(pk=real_questao_id)
                        prova_respondida_obj = ProvaRespondida.objects.create(
                            aluno=aluno,
                            questao=questao,
                            resposta=resposta,
                            prova_completa=prova_completa,
                            simulado=simulado,
                        )
                        prova_respondida_obj.set_acerto()

                prova_completa.simulado = prova_respondida_obj.simulado

                # Deactivated QuestaoRespondida for DEV
                # questao_respondida = QuestaoRespondida()
                # questao_respondida.set_questoes_ja_respondidas(aluno)
                prova_completa.gera_relatorio()
                prova_completa.deleta_respostas()
                prova_completa_url = reverse(
                    "provas:prova-completa", args=[prova_completa.id]
                )
                context = {"prova_completa_url": prova_completa_url}
                cache.delete(f"aluno_provas_feitas_{aluno.id}")
                cache.delete(f"turmas_graph_{aluno.id}")
            return render(request, "provas/prova-respondida.html", context)


def prova_completa(request, prova_id):
    prova_completa_obj = ProvaCompleta.objects.get(pk=prova_id)
    ranking_piores = {
        Conteudo.objects.get(pk=conteudo_id).nome: quantidade
        for conteudo_id, quantidade in sorted(
            prova_completa_obj.ranking_piores_conteudos.items(),
            key=lambda x: x[1],
            reverse=True,
        )
    }
    ranking_melhores = {
        Conteudo.objects.get(pk=conteudo_id).nome: quantidade
        for conteudo_id, quantidade in sorted(
            prova_completa_obj.ranking_melhores_conteudos.items(),
            key=lambda x: x[1],
            reverse=True,
        )
    }
    acertos = prova_completa_obj.acertos
    erros = prova_completa_obj.erros
    data = prova_completa_obj.data_feita
    context = {
        "ranking_piores": ranking_piores,
        "ranking_melhores": ranking_melhores,
        "erros": erros,
        "acertos": acertos,
        "data": data,
    }

    return render(request, "provas/prova-completa.html", context)


@login_required
@user_has_tag("is_professor")
def criar_prova_professor(request):
    cache_key = f"criar_prova_professor"
    cached_page = cache.get(cache_key)

    if cached_page:
        return HttpResponse(cached_page)

    materias = Materia.objects.all().prefetch_related("sub_materia__conteudo__questoes")
    materias_data = []
    for materia in materias:
        materias_dict = {"nome": materia.nome, "sub_materias": []}
        for sub_materia in materia.sub_materia.all():
            sub_materia_dict = {
                "nome": sub_materia.nome,
                "conteudos": [],
            }
            for conteudo in sub_materia.conteudo.all():
                conteudo_dict = {
                    "id": conteudo.id,
                    "nome": conteudo.nome,
                    "questoes": set(conteudo.questoes.all()),
                }
                sub_materia_dict["conteudos"].append(conteudo_dict)
            materias_dict["sub_materias"].append(sub_materia_dict)
        materias_data.append(materias_dict)

    context = {
        "materias_data": materias_data,
    }
    response = render(request, "provas/criacao-prova-professor.html", context)
    cache.set(cache_key, response.content, 60 * 10)
    return response


@login_required
@user_has_tag("is_professor")
def get_questoes_by_conteudo_id(request, conteudo_id):
    """
    Retorna um Json com os dados de cada questao do conteudo.
    """
    conteudo = Conteudo.objects.get(id=conteudo_id)
    questoes_list = Questao.objects.filter(conteudo=conteudo)
    data = [
        {
            "id": q.id,
            "enunciado": q.enunciado,
            "identificador": q.identificador_unico,
            "nivel": "facil"
            if q.nivel.nivel <= 15
            else "medio"
            if q.nivel.nivel < 30
            else "difícil",
        }
        for q in questoes_list
    ]
    return JsonResponse(data, safe=False)

app/provas/templates/provas/criacao-prova-professor.html
<!-- prettier-ignore -->
{% extends 'static/platform-base.html' %} {% block title %} Criar prova {% endblock %}
{% block content %} {% if materias_data %}

<div class="materias">
  {% for materia in materias_data %}
  <div class="materia">
    {{ materia.nome }}
    <div class="conteudo hidden">
      <ul>
        {% for sub_materia in materia.sub_materias %}
        <li>
          {{ sub_materia.nome }}
          <ul>
            {% for conteudo in sub_materia.conteudos %}
            <li>
              <a
                href="{% url 'provas:get_questoes_by_conteudo_id' conteudo.id %}"
              >
                {{ conteudo.nome }}
              </a>
            </li>
            {% endfor %}
          </ul>
        </li>
        {% endfor %}
      </ul>
    </div>
  </div>
  {% endfor %}
</div>
{% endif %} {% endblock %}

app/provas/templates/provas/escolha-prova.html
{% extends 'static/platform-base.html'%} {% block title %} Escolha sua prova
{%endblock %} {% block content %}
<script>
  document.addEventListener("DOMContentLoaded", function () {
    let select = document.getElementById("tipoProvaSelect");
    select.addEventListener("change", function () {
      let selectedValue = this.value;

      let forms = document.getElementsByClassName("prova-customizavel");
      for (let form of forms) {
        form.style.display = "none";
      }

      if (selectedValue === "simulado") {
        document.getElementById("simuladoForm").style.display = "block";
      } else if (selectedValue === "materia_escolhida") {
        document.getElementById("provaForm").style.display = "block";
        document.getElementById("simuladoForm").style.display = "none";
      }
    });
  });
</script>
<div class="prova-form-container">
  {% if messages %}
  <div class="message">
    <div class="alert alert-danger">
      {% for message in messages %}{{ message }} <br />{% endfor %}
    </div>
  </div>
  {% endif %}

  <select id="tipoProvaSelect">
    <option value="simulado">Simulado</option>
    <option value="materia_escolhida">Lista Adaptavel</option>
  </select>

    <div id='provaForm' class="prova-customizavel" style="display: none;">
        <form action="{% url 'provas:prova-choose' %}" method="post">
            {% csrf_token %}
            <div class="num_questoes">
                <label for="num_questoes">Numero de questões</label> <br>
                {{ choose_prova.num_questoes_prova }}
            </div>
            <div>
                <label for="materias">Materias</label>
                {{ choose_prova.materias }}
            </div>
            <input type="text" name="tipo_prova" value="materia_escolhida" style="display: none;">
            <button type="submit">Realizar prova</button>
        </form>
    </div>

    <div id="simuladoForm" class="simulado-customizavel" style="display: block;">
        <form action="{% url 'provas:prova-choose' %}" method="post">
            {% csrf_token %}

            <div class="num_questoes">
                <label for="num_questoes_simulado">Numero de questões</label> <br>
                {{ choose_prova.num_questoes_simulado }}
            </div>
            <div>
                <label for="simulados">Simulado</label>
                {{ choose_prova.simulados }}
            </div>
            <input type="text" name="tipo_prova" value="simulado" style="display: none;">
            <button type="submit">Realizar prova</button>
        </form>
    </div>
</div>

{% endblock %}

app/provas/templates/provas/prova-completa.html
{% extends 'static/prova-base.html'%}


{% block title %}
   Relatorio Prova
{% endblock %}


{% block content %}
<a href="{% url 'usuarios:aluno-provas-feitas' %}">
    <button> Voltar </button>
</a>
    <h1>Prova </h1>
    <h1>Ranking Conteudos mais errados</h1>
    <ol>
        {% for conteudo, erros  in ranking_piores.items %}
            <li>Conteudo: {{conteudo}} --- Erros: {{erros}}</li>
        {% endfor %}
    </ol>
    <h1>Ranking Conteudos mais acertados</h1>
    <ol>
        {% for conteudo, acertos  in ranking_melhores.items %}
            <li>Conteudo: {{conteudo}} --- Acertos: {{acertos}}</li>
        {% endfor %}
    </ol>
    <h1>Acertos por dificuldade</h1>
    <ul>
        {% for nivel, acerto in acerto_dificuldade.items %}
        <li>Nivel: {{nivel}} Acertos:{{acerto}}</li>
        {% endfor %}
    </ul>
    <h1>Data Prova</h1>
    {{data}}
    <h1>Acertos/Erros</h1>
    <p> Acertos: {{acertos}} Erros: {{erros}}</p>
{% endblock %}

app/provas/templates/provas/prova-respondida.html
{% extends 'static/prova-base.html' %}
{% block title %} Prova enviada {% endblock %}

{% block content %}

<div>
    <h2>
        Prova enviada {{ user.nome }}, gerando relatorio 
        {% if prova_completa_url %} 
            <a href="{{ prova_completa_url }}">confira aqui!</a>
        {% endif %}
    </h2>
</div>

{% endblock %}

app/provas/templates/provas/prova.html
{% extends 'static/prova-base.html'%}
{% load provatag %}

{% block title %}
    Prova
{% endblock %}


{% block content %}
{% if materias %}
    {% for materia in materias %}
    <div>
        <p>{{ materia.nome }}</p> <br>
    </div>
    {% endfor %}
{% endif %}

<form action="{% url 'provas:prova-respondida' %}" method="post">
    {% csrf_token %}
    {% if questoes %}
    <div>
        {% for questao in questoes %}
            <p>{{forloop.counter}}) {{questao.enunciado}}</p>
            {% if questao.imagem_enunciado %}
                <img src="{{ questao.imagem_enunciado.url }}" alt="{{ questao.conteudo }} Imagem"> <br>
            {% endif %}
            {% with opcoes_imagem=questao.opcoes_imagem.opcoes_imagem_dict %}
                {% for opcao in questao.opcoes %}
                    {% with letra=forloop.counter0|opcao_em_letra %}
                        {% if opcao == '[IMG]' %}
                            <input type="radio" name="questao_id-{{questao.id}}" value="{{ forloop.counter0|opcao_em_letra }}">
                            {{ forloop.counter0|opcao_em_letra }}) <img src="{{ opcoes_imagem|get_dictionary_item:letra }}" alt="Imagem {{ forloop.counter0|opcao_em_letra }}" height="40px"> <br>
                            {% else %}
                            <input type="radio" name="questao_id-{{questao.id}}" value="{{ forloop.counter0|opcao_em_letra }}">
                            {{forloop.counter0|opcao_em_letra}}) {{ opcao }} <br>
                        {% endif %}
                    {% endwith %}
                {% endfor %}
            {% endwith %}
        {% endfor %}
    </div>
    {% endif %}
    <button type="submit">Enviar respostas</button>
</form>
{% endblock %}