app/enem10x/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include('home.urls')),
    path('admin/', admin.site.urls),
    path('provas/', include("provas.urls")),
    path('usuarios/', include("usuarios.urls")),
    path('__debug__/', include("debug_toolbar.urls")),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/home/urls.py
from django.urls import path
from home.views import home_view



# App name for refering in other code parts
app_name = 'home'

# Urls 
urlpatterns = [
    path('', home_view, name='home'),

]

app/provas/urls.py
from django.urls import path
from provas.views import (
    prova_choose,
    prova_respondida,
    prova_completa,
    criar_prova_professor,
    get_questoes_by_conteudo_id,
)

# App name for refering in other code parts
app_name = "provas"

# Urls
urlpatterns = [
    path("", prova_choose, name="prova-choose"),
    path("respondida/", prova_respondida, name="prova-respondida"),
    path("completa/<int:prova_id>/", prova_completa, name="prova-completa"),
    path("criar/", criar_prova_professor, name="criar-prova-professor"),
    path(
        "get_provas/<int:conteudo_id>",
        get_questoes_by_conteudo_id,
        name="get_questoes_by_conteudo_id",
    ),
]

app/usuarios/urls.py
from django.urls import path
from usuarios.views import (
    notas_graph,
    signup,
    signupsucess,
    logout_view,
    login_view,
    filter_graph_time,
    platform_view,
    professor_turmas_view,
    criar_turma_view,
    professor_turma_view,
    entra_turma,
    delete_turma,
    aluno_turma_view,
    aluno_turmas_view,
    remover_aluno,
    sair_turma_aluno,
    aluno_provas_feitas,
    user_profile,

)


app_name = "usuarios"

urlpatterns = [
    path("plataforma/", platform_view, name="plataforma"),
    path("plataforma/perfil", user_profile, name="user-profile"),
    path("plataforma/grafico-notas", notas_graph, name="graficos"),
    path("plataforma/filter-graph-time/", filter_graph_time, name="graph-filter"),
    path(
        "plataforma/professor/turmas/", professor_turmas_view, name="professor-turmas"
    ),
    path("plataforma/professor/criar-turma/", criar_turma_view, name="criar-turma"),
    path(
        "plataforma/professor/turma/<int:turma_id>",
        professor_turma_view,
        name="professor-turma",
    ),
    path(
        "plataforma/professor/turma/remover-aluno/<int:turma_id>/<int:aluno_id>",
        remover_aluno,
        name="remover-aluno",
    ),
    path(
        "plataforma/aluno/turma/sair/<int:turma_id>/<int:aluno_id>",
        sair_turma_aluno,
        name="aluno-sair-turma",
    ),
    path("plataforma/aluno/turmas/", aluno_turmas_view, name="aluno-turmas"),
    path("plataforma/aluno/turma/<int:turma_id>", aluno_turma_view, name="aluno-turma"),
    path(
        "plataforma/aluno/provas/", aluno_provas_feitas, name='aluno-provas-feitas'
    ),
    path("plataforma/turma/delete/<int:turma_id>", delete_turma, name="delete-turma"),
    path("plataforma/turma/entrar/", entra_turma, name="entrar-turma"),
    path("login/", login_view, name="login"),
    path("signup/", signup, name="signup"),
    path("conta-criada/", signupsucess, name="signup-sucess"),
    path("logout/", logout_view, name="logout"),
]

app/usuarios/views.py
from django.shortcuts import render, redirect
from usuarios.funcs import NotaChart, NotaFilteredChart, MediaQuery
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout
from usuarios.forms import AccountCreationForm, CriarTurmaForm
from django.contrib import messages
from materiais.models import ProvaCompleta
from django.http import JsonResponse, HttpResponseForbidden, HttpResponse
from usuarios.models import Turma, Professor, Aluno, Escola, CordenadorEscola
from usuarios.decorators import user_has_tag
from uuid import uuid4
from django.shortcuts import get_object_or_404
from django.views.decorators.cache import cache_page
from django.core.cache import cache
from django.urls import reverse

# Create your views here.


# CACHE AQUI
@login_required
@user_has_tag("is_aluno")
def notas_graph(request):
    if request.user.is_aluno or request.user.is_admin:
        aluno = request.user.aluno
        cache_key = f"notas_graph_{aluno.id}"
        cached_page = cache.get(cache_key)
        if cached_page:
            return HttpResponse(cached_page)
        (
            data_mat,
            data_nat,
            data_lin,
            data_hum,
            months_mat,
            months_nat,
            months_lin,
            months_hum,
        ) = NotaChart(request.user.aluno)
        media_mat, media_nat, media_lin, media_hum = MediaQuery(aluno)
        context = {
            "data_mat": data_mat,
            "months_mat": months_mat,
            "data_nat": data_nat,
            "months_nat": months_nat,
            "data_lin": data_lin,
            "months_lin": months_lin,
            "data_hum": data_hum,
            "months_hum": months_hum,
            "media_mat": media_mat,
            "media_nat": media_nat,
            "media_lin": media_lin,
            "media_hum": media_hum,
        }
        response = render(request, "usuarios/notas-graph.html", context)
        cache.set(cache_key, response.content, 60 * 10)
        return response
    else:
        return HttpResponseForbidden("403 forbidden")


@login_required
def platform_view(request):
    if request.user.is_authenticated:
        return render(request, "static/platform-base.html")
    else:
        return redirect("usuarios:login")


@login_required
def filter_graph_time(request):
    months = request.GET.get("filter", None)
    months = int(months) if months else None
    result = NotaFilteredChart(request.user, months)
    data_mat = result["data_mat"]
    data_nat = result["data_nat"]
    data_lin = result["data_lin"]
    data_hum = result["data_hum"]
    months_mat = result["months_mat"]
    months_nat = result["months_nat"]
    months_lin = result["months_lin"]
    months_hum = result["months_hum"]
    context = {
        "graph_mat": {"newLabels": months_mat, "newData": data_mat},
        "graph_nat": {"newLabels": months_nat, "newData": data_nat},
        "graph_lin": {"newLabels": months_lin, "newData": data_lin},
        "graph_hum": {"newLabels": months_hum, "newData": data_hum},
    }
    return JsonResponse(context)


def login_view(request):
    if request.user.is_authenticated:
        return redirect("usuarios:plataforma")
    elif request.method == "POST":
        email = request.POST["email"]
        password = request.POST["password"]
        user = authenticate(request, email=email, password=password)
        if user is not None:
            login(request, user)
            return redirect("usuarios:plataforma")
        return render(
            request, "usuarios/login.html", {"message": "Email ou senha inválidos"}
        )
    return render(request, "usuarios/login.html")


def signup(request, *args, **kwargs):
    if request.method == "POST":
        form = AccountCreationForm(request.POST)
        if form.is_valid():
            # Cria conta com Account Form
            form.save()
            email = form.cleaned_data["email"]
            password = form.cleaned_data["password2"]
            auth_user = authenticate(request, email=email, password=password)
            if auth_user is not None:
                # Se o usuario foi criado com sucesso ja loga
                login(request, auth_user)
                return redirect("usuarios:signup-sucess")
        context = {"form": form}
        return render(request, "usuarios/signup.html", context)

    form = AccountCreationForm()
    context = {
        "form": form,
    }
    return render(request, "usuarios/signup.html", context)


@login_required
def professor_turmas_view(request):
    if request.user.is_professor:
        professor = request.user.professor
        cache_key = f"professor_turmas_view_{professor.id}"
        cached_page = cache.get(cache_key)
        if cached_page:
            return HttpResponse(cached_page)
        turmas_1 = Turma.objects.filter(criador=professor)
        turmas_2 = professor.turmas.all()
        turmas = set(turmas_1) | set(turmas_2)
        context = {"turmas": turmas, "professor": professor}
        response = render(request, "usuarios/turmas.html", context)
        cache.set(cache_key, response.content, 60 * 10)
        return response
    else:
        return HttpResponseForbidden("saia")


@login_required
@user_has_tag("is_aluno")
def aluno_turmas_view(request):
    if request.user.is_aluno:
        aluno = request.user.aluno
        cache_key = f"aluno_turmas_view_{aluno.id}"
        cached_page = cache.get(cache_key)
        if cached_page:
            return HttpResponse(cached_page)

        turmas = Turma.objects.filter(alunos=aluno)
        context = {"turmas": turmas, "aluno": aluno}
        response = render(request, "usuarios/turmas.html", context)
        cache.set(cache_key, response.content, 60 * 10)
        return response
    else:
        return HttpResponseForbidden("Forbidden, don't try again.")


@login_required
@user_has_tag("is_professor")
def criar_turma_view(request):
    professor_criador = Professor.objects.get(usuario=request.user)
    if request.method == "POST":
        form = CriarTurmaForm(professor_criador, request.POST)
        if form.is_valid():
            turma = form.save(commit=False)
            turma.codigo = uuid4()
            turma.criador = professor_criador
            turma.save()
            messages.add_message(
                request,
                messages.SUCCESS,
                f'{professor_criador.usuario.nome} meus parabens "{turma.nome}" criada com sucesso! ',
            )
            cache.delete(f"professor_turmas_view_{professor_criador.id}")
            return redirect(reverse("usuarios:professor-turmas"))
    form = CriarTurmaForm(professor_criador)
    context = {"form": form}
    return render(request, "usuarios/create-turma.html", context)


@login_required
@user_has_tag("is_professor")
def professor_turma_view(request, turma_id):
    professor = Professor.objects.get(usuario=request.user)
    turma = get_object_or_404(Turma, id=turma_id)

    if (
        not turma.professores.filter(id=professor.id).exists()
        and turma.criador != professor
    ):
        return HttpResponseForbidden("403 Forbidden")

    context = {
        "turma": turma,
        "professor": professor,
    }
    return render(request, "usuarios/turma.html", context)


@login_required
@user_has_tag("is_aluno")
def aluno_turma_view(request, turma_id):
    aluno = Aluno.objects.get(usuario=request.user)
    turma = get_object_or_404(Turma, id=turma_id)
    if not turma.alunos.filter(id=aluno.id).exists():
        return HttpResponseForbidden("403 Forbidden")
    context = {
        "turma": turma,
        "aluno": aluno,
    }
    return render(request, "usuarios/turma.html", context)


@login_required
def signupsucess(request):
    return render(request, "usuarios/signup-sucess.html")


@login_required
def logout_view(request):
    logout(request)
    return redirect("home:home")


@login_required
def entra_turma(request):
    if request.user.is_aluno or request.user.is_professor:
        usuario = request.user
        if request.method == "POST":
            codigo = request.POST["codigo"]
            turma = get_object_or_404(Turma, codigo=codigo)
            if request.user.is_aluno:
                if turma.criador.get_remaining_alunos() <= 0:
                    messages.add_message(
                        request,
                        messages.ERROR,
                        "Esse professor ja atingiu seu limite de alunos.",
                    )
                    return render(request, "usuarios/erro.html")
                else:
                    aluno = request.user.aluno
                    cache_key = f"aluno_turmas_{aluno.id}"
                    turma.alunos.add(aluno)
                    turma.criador.alunos += 1
                    turma.criador.save()
                    cache.delete(cache_key)
                    messages.add_message(
                        request,
                        messages.SUCCESS,
                        f"{usuario.nome} voce entrou na {turma.nome} com sucesso!",
                    )
                    return redirect("usuarios:aluno-turmas")
            if request.user.is_professor:
                professor = request.user.professor
                cache_key = f"professor_turmas_{professor.id}"
                turma.professores.add(professor)
                messages.add_message(
                    request,
                    messages.SUCCESS,
                    f"{usuario.nome} você entrou na {turma.nome} com sucesso !",
                )
                cache.delete(cache_key)
                return redirect("usuarios:professor-turmas")
        return render(request, "usuarios/entrar-turma.html")
    else:
        return HttpResponseForbidden(
            "Você não tem permissão para acessar esta página. Esse acesso será rastreado.."
        )


@login_required
def delete_turma(request, turma_id):
    turma = Turma.objects.get(id=turma_id)

app/usuarios/templates/usuarios/create-turma.html
{% block title %} {% endblock %} 
{% load static %} {% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Criar Turma</title>
    <link rel="stylesheet" href="{% static 'usuarios/style.css' %}">
</head>
    <body class="create-turma-container">
        <button onclick="window.history.back()">Voltar</button>
        <div class="create-turma">
            <form action="{% url 'usuarios:criar-turma' %}" method="post">
                {% csrf_token %}
                <div class="form">
                    <div class="header">
                        <h1>Nome da turma</h1>
                    </div>
                    <div class="input">
                        {{ form.as_p }}
                    </div>
                    <button type="submit">Criar</button>
                </div>
            </form>
        </div>
    </body>
</html>
{% endblock %}

app/usuarios/templates/usuarios/entrar-turma.html
{% extends 'static/user-form-base.html' %} {% block title %} Entrar Turma 
{% endblock %} {% load static %} {% block content %}
<div class="codigo-container">
  <button onclick="window.history.back()" class="back">voltar</button>
  <h1>Entrar em uma turma</h1>

  <form action="{% url 'usuarios:entrar-turma' %}" method="post">
    {% csrf_token %}
    <label for="codigo">Digite o codigo</label>
    <input type="text" name="codigo" class="turma-codigo-input" />
    <button type="submit">Entrar</button>
  </form>
</div>
{% endblock %}

app/usuarios/templates/usuarios/erro.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Error</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'usuarios/style.css' %}">
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js"
      integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r"
      crossorigin="anonymous"
    ></script>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.16/jquery.mask.min.js"></script>
</head>
<body>
    <button type="button" onclick="window.history.back()">
        Voltar
    </button>
    {% if messages %}
    <div class="message">
        <div class="alert alert-info">{% for message in messages %} {{message}} {% endfor %}</div>
    </div>
    {% endif %}
</body>
</html>

app/usuarios/templates/usuarios/notas-graph.html
{% extends 'static/platform-base.html' %} {% block title %} Usuario {% endblock %}
{% block content %} {% load static %}
<div class="filters">
  <select id="timeFilter">
    <option value="">Todas</option>
    <option value="1">Últimos mes</option>
    <option value="6">Últimos 6 meses</option>
    <option value="12">Último ano</option>
  </select>
</div>
<div class="chart-container">
  <div class="chart-display">
    <h1>Nota matematica</h1>
    <canvas id="nota-matematica-tempo" style="height: 300px; width: 300px; margin-left: 20px"></canvas>
    <script>
      const ctx1 = document.getElementById("nota-matematica-tempo");
      const meses_mat_str = "{{months_mat|safe}}".replace(/'/g, '"');
      const meses_mat = JSON.parse(meses_mat_str);
      const dataMat = JSON.parse("{{data_mat|safe}}");
      const MediaMat = Array(meses_mat.length).fill(parseFloat("{{media_mat}}"))

      const myChart1 = new Chart(ctx1, {
        type: "line",
        data: {
          labels: meses_mat,
          datasets: [
            {
              label: "Nota Matematica",
              data: dataMat,
              fill: false,
              borderColor: "rgb(75, 192, 192)",
              tension: 0.1,
            }, {
              label: "Media Matematica",
              data: MediaMat,
              fill: false,
              borderColor: "rgb(163, 236, 118)",
              tension: 0.1,
              pointRadius: 0,
            }],
        },
        options: {
          responsive: true,
          // for developing only, set true to production for better performance
          animation: true,
        },
      });
    </script>
  </div>
  <div class="chart-display">
    <h1>Nota Natureza</h1>
    <canvas id="nota-nat-tempo" style="height: 300px; width: 300px; margin-left: 20px"></canvas>
    <script>
      const ctx2 = document.getElementById("nota-nat-tempo");
      const meses_nat_str = "{{months_nat|safe}}".replace(/'/g, '"');
      const meses_nat = JSON.parse(meses_nat_str);
      const dataNat = JSON.parse("{{data_nat|safe}}");
      const MediaNat = Array(meses_nat.length).fill(parseFloat("{{media_nat}}"))


      const myChart2 = new Chart(ctx2, {
        type: "line",
        data: {
          labels: meses_nat,
          datasets: [
            {
              label: "Nota Ciencias da Natureza ",
              data: dataNat,
              fill: false,
              borderColor: "rgb(75, 192, 192)",
              tension: 0.1,
            },
            {
              label: "Media Natureza",
              data: MediaNat,
              fill: false,
              borderColor: "rgb(163, 236, 118)",
              tension: 0.1,
              pointRadius: 0,
            }
          ],
        },

        options: {
          responsive: true,
          // for developing only, set true to production for better performance
          animation: true,
        },
      });
    </script>
  </div>
  <div class="chart-display">
    <h1>Nota Linguagens</h1>
    <canvas id="nota-lin-tempo" style="height: 300px; width: 300px; margin-left: 20px"></canvas>
    <script>
      const ctx3 = document.getElementById("nota-lin-tempo");
      const meses_lin_str = "{{months_lin|safe}}".replace(/'/g, '"');
      const meses_lin = JSON.parse(meses_lin_str);
      const dataLin = JSON.parse("{{data_lin|safe}}");
      const mediaLin = Array(meses_lin.length).fill(parseFloat("{{media_lin}}"))


      const myChart3 = new Chart(ctx3, {
        type: "line",
        data: {
          labels: meses_lin,
          datasets: [
            {
              label: "Nota  Linguagens",
              data: dataLin,
              fill: false,
              borderColor: "rgb(75, 192, 192)",
              tension: 0.1,
            },
            {
              label: "Media Linguagens",
              data: mediaLin,
              fill: false,
              borderColor: "rgb(163, 236, 118)",
              tension: 0.1,
              pointRadius: 0,
            }
          ],
        },

        options: {
          responsive: true,
          // for developing only, set true to production for better performance
          animation: true,
        },
      });
    </script>
  </div>
  <div class="chart-display">
    <h1>Nota Humanas</h1>
    <canvas id="nota-humanas-tempo" style="height: 300px; width: 300px; margin-left: 20px"></canvas>
    <script>
      const ctx4 = document.getElementById("nota-humanas-tempo");
      const meses_hum_str = "{{months_hum|safe}}".replace(/'/g, '"');
      const meses_hum = JSON.parse(meses_hum_str);
      const dataHum = JSON.parse("{{data_hum|safe}}");
      const mediaHum = Array(meses_hum.length).fill(parseFloat("{{media_hum}}"))


      const myChart4 = new Chart(ctx4, {
        type: "line",
        data: {
          labels: meses_hum,
          datasets: [
            {
              label: "Nota Ciencias Humanas",
              data: dataHum,
              fill: false,
              borderColor: "rgb(75, 192, 192)",
              tension: 0.1,
            },
            {
              label: "Media Humanas",
              data: mediaHum,
              fill: false,
              borderColor: "rgb(163, 236, 118)",
              tension: 0.1,
              pointRadius: 0,
            }
          ],
        },

        options: {
          responsive: true,
          // for developing only, set true to production for better performance
          animation: true,
        },
      });
    </script>
  </div>
</div>
<script src="{% static 'usuarios/js/graph.js' %}"></script>
{% if provas_completas %}
<div>
  {% for prova in provas_completas %}
  <p>
    <a href="{% url 'provas:prova-completa' prova.id %}">Prova: {{ forloop.counter }} {{prova.data_feita}}</a>
  </p>
  <br />
  {% endfor %}
</div>
{% endif %} {% endblock %}

app/usuarios/templates/usuarios/provas-feitas.html
{% extends 'static/platform-base.html' %} {% block title %} Usuario {% endblock %}
{% load static %}
{% block content %} 
<div class="prova-create-container">
    {% if user.is_professor %}
    <button type="button">
      <a href="{% url 'provas:prova-choose' %}" class="no-text-decoration">
        Criar prova
      </a>
    </button>
    {% elif user.is_aluno %}
    <button type="button">
      <a href="{% url 'provas:prova-choose' %}" class="no-text-decoration">
        Realizar prova
      </a>
    </button>
    {% endif %}
</div>

{% if provas_feita_do_usuario %}
    {% for prova in provas_feita_do_usuario %}
      <div>
          <div>
              {{prova}} {{prova.nota}} {{prova.data_feita}} <a href="{% url 'provas:prova-completa' prova.id %}">relatorio</a>
          </div>
      </div>
    {% endfor %}
{% else %}
  <div>
      Nenhuma prova realizada faca uma agora clicando no botao acima.
  </div>
{% endif %}

{% endblock %}

app/usuarios/templates/usuarios/signup-sucess.html
{% extends 'static/user-form-base.html' %} {% block title %} Cadastro {% endblock %} 
{% block content %} 
{% load static %}
<div class="account-form">
    <div class="form-message">
        <div class="alert alert-check">
            <p>{{ user.nome }} cadastrado com sucesso!</p> <br>
            <p> Confirme seu email para usar a plataforma! <br>
            Link para verificação. <br>
            </p>
            
        </div>
    </div>
</div>
<div>
    <div>
        <a href="{% url 'home:home' %}">
            <button type="button" class="btn btn-warning">Home</button>
          </a>
    </div>
</div>
{% endblock %}

app/usuarios/templates/usuarios/turma.html
{% extends 'static/platform-base.html' %} {% block title %} Turma - {{turma.nome}}
{% endblock %} {% block content %} {% load static %}
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script>
  $(document).ready(function () {
    $("#toggleButton").on("click", function () {
      $("#uuidField").toggleClass("blur-text");

      if ($("#uuidField").hasClass("blur-text")) {
        $(this)
          .find("i")
          .removeClass("fa-regular fa-eye-slash")
          .addClass("fa-regular fa-eye");
      } else {
        $(this)
          .find("i")
          .removeClass("fa-regular fa-eye")
          .addClass("fa-regular fa-eye-slash");
      }
    });
  });
  $(document).ready(function () {
    var myToolTip = new bootstrap.Tooltip(document.getElementById('uuidLink'),{
      trigger: "manual"
    });

    document
      .getElementById("uuidLink")
      .addEventListener("click", function (event) {
        event.preventDefault(); // Prevent the <a> </a> works as a <a> </a>
        // Copy algorithm

        var textArea = document.createElement("textarea");
        textArea.value = event.target.textContent;
        document.body.appendChild(textArea);
        textArea.select();
        document.execCommand("copy");
        document.body.removeChild(textArea);

        myToolTip.show();
        setTimeout(() => {
          myToolTip.hide();
        }, 2000);
      });
  });
</script>

<link rel="stylesheet" href="{% static 'usuarios/turma.css' %}" />
<div class="message">
  {% if messages %}
  <div class="alert alert-info">
    {% for message in messages %} {{ message }} {% endfor %}
  </div>
  {% endif %}
</div>
<div class="container">
  <div class="header">
    <h1>{{ turma.nome }}</h1>
  </div>
  <div class="body">
    <h2>Professores</h2>
    {{ turma.criador }} - Criador {% for professor in turma.professores.all %}
    <h6>{{ professor }}</h6>
    {% endfor %}
    <h2>Alunos</h2>
    <ul class="aluno-list">
      {% for aluno in turma.alunos.all %}
      <li>
        <i class="bx bx-user"></i>
        <a href="" class="no-text-decoration">{{ aluno.usuario }}</a>
        {% if professor == turma.criador %}
        <button type="button">
          <a
            href="{% url 'usuarios:remover-aluno' turma.id aluno.id %}"
            class="no-text-decoration"
            >Remover aluno</a
          >
        </button>
        {% endif %}
      </li>
      {% endfor %}
    </ul>
  </div>
  {% if user.is_professor %}
  <div class="footer">
    <h2>Codigo de acesso:</h2>
    <p class="info-text">
      clique para copiar.
    </p>
    <div class="codigo-container">
      <div class="codigo-text">
        <span id="uuidField" class="blur-text"
          ><a
            href="#"
            id="uuidLink"
            data-bs-placement="top"
            data-bs-custom-class="custom-tooltip"
            data-bs-title="Copied!"
            class="no-text-decoration"
            >{{turma.codigo}}</a
          ></span
        >
      </div>
      <div class="codigo-reveal">
        <button type="button" class="reveal-button" id="toggleButton">
          <i class="fa-regular fa-eye"></i>
        </button>
      </div>
    </div>
  </div>
  <div class="turma-actions">
    <div class="action">
      <button type="button" class="btn btn-danger">
        <a
          href="{% url 'usuarios:delete-turma' turma.id %}"
          class="no-text-decoration"
          >Deletar Turma</a
        >
      </button>
    </div>
  </div>
  {% elif user.is_aluno %}
  <div class="turma-actions">
    <div class="action">
      <button type="button" class="btn btn-danger">
        <a
          href="{% url 'usuarios:aluno-sair-turma' turma.id aluno.id %}"
          class="no-text-decoration"
          >Sair da turma</a
        >
      </button>
    </div>
  </div>
  {% endif %}
</div>
{% endblock %}

app/usuarios/templates/usuarios/turmas.html
{% extends 'static/platform-base.html' %} {% block title %} Turmas {% endblock %}
{% block content %}
<style>
  .alunos-restantes {
    margin-left: 60px;
  }
</style>
<div class="turma-create-container">
  {% if user.is_professor %}
  <button type="button">
    <a href="{% url 'usuarios:criar-turma' %}" class="no-text-decoration">
      Criar turma
    </a>
  </button>
  <div class="alunos-restantes">
    <span> Alunos restantes : {{ professor.get_remaining_alunos }}</span>
  </div>
  {% elif user.is_aluno %}
  <button type="button">
    <a href="{% url 'usuarios:entrar-turma' %}" class="no-text-decoration">
      Entrar
    </a>
  </button>
  {% endif %}
</div>

</div>
<div class="turmas-container">
  {% if messages %}
  <div class="message">
    <div class="alert alert-info">
      {% for message in messages %}{{ message }} <br />{% endfor %}
    </div>
  </div>
  {% endif %}
  {% if turmas %}
  {% for turma in turmas %}
  <div class="turma-box">
    {% if user.is_professor %}
    <a href="{% url 'usuarios:professor-turma' turma.id %}" class="turma-box-link no-text-decoration">
      {% elif user.is_aluno %}
      <a href="{% url 'usuarios:aluno-turma' turma.id %}" class="turma-box-link no-text-decoration">
        {% endif %}
        <div class="turma-box-header">
          <h2><i class="bi bi-pass"></i>{{ turma.nome }}</h2>
        </div>
        <div class="turma-body">
          <h5>{{ turma.get_qtd_alunos }} Alunos</h5>
        </div>
      </a>
  </div>
  {% endfor %}
  {% endif %}
</div>
{% endblock %}