app/enem10x/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include('home.urls')),
    path('admin/', admin.site.urls),
    path('provas/', include("provas.urls")),
    path('usuarios/', include("usuarios.urls")),
    path('__debug__/', include("debug_toolbar.urls")),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/home/urls.py
from django.urls import path
from home.views import home_view



# App name for refering in other code parts
app_name = 'home'

# Urls 
urlpatterns = [
    path('', home_view, name='home'),

]

app/usuarios/urls.py
from django.urls import path
from usuarios.views import (
    notas_graph,
    signup,
    signupsucess,
    logout_view,
    login_view,
    filter_graph_time,
    platform_view,
    professor_turmas_view,
    criar_turma_view,
    professor_turma_view,
    entra_turma,
    delete_turma,
    aluno_turma_view,
    aluno_turmas_view,
    remover_aluno,
    sair_turma_aluno,
    aluno_provas_feitas,
    user_profile,

)


app_name = "usuarios"

urlpatterns = [
    path("plataforma/", platform_view, name="plataforma"),
    path("plataforma/perfil", user_profile, name="user-profile"),
    path("plataforma/grafico-notas", notas_graph, name="graficos"),
    path("plataforma/filter-graph-time/", filter_graph_time, name="graph-filter"),
    path(
        "plataforma/professor/turmas/", professor_turmas_view, name="professor-turmas"
    ),
    path("plataforma/professor/criar-turma/", criar_turma_view, name="criar-turma"),
    path(
        "plataforma/professor/turma/<int:turma_id>",
        professor_turma_view,
        name="professor-turma",
    ),
    path(
        "plataforma/professor/turma/remover-aluno/<int:turma_id>/<int:aluno_id>",
        remover_aluno,
        name="remover-aluno",
    ),
    path(
        "plataforma/aluno/turma/sair/<int:turma_id>/<int:aluno_id>",
        sair_turma_aluno,
        name="aluno-sair-turma",
    ),
    path("plataforma/aluno/turmas/", aluno_turmas_view, name="aluno-turmas"),
    path("plataforma/aluno/turma/<int:turma_id>", aluno_turma_view, name="aluno-turma"),
    path(
        "plataforma/aluno/provas/", aluno_provas_feitas, name='aluno-provas-feitas'
    ),
    path("plataforma/turma/delete/<int:turma_id>", delete_turma, name="delete-turma"),
    path("plataforma/turma/entrar/", entra_turma, name="entrar-turma"),
    path("login/", login_view, name="login"),
    path("signup/", signup, name="signup"),
    path("conta-criada/", signupsucess, name="signup-sucess"),
    path("logout/", logout_view, name="logout"),
]

app/home/models.py
from django.db import models

# Create your models here.

app/home/views.py
from django.shortcuts import render




# Create your views here.
def home_view(request):
    return render(request, 'home/home-menu.html')
    

app/home/templates/home/home-menu.html
{% extends 'static/home-base.html' %} {% load static %} {% block content %}

<div id="navbar">
  <div id="leftside">
    <a href="{% url 'home:home' %}">
      <img src="{% static 'home/Logo.png' %}" alt="Logo" />
    </a>
    <img id="linha" src="{% static 'home/line.svg' %}" alt="Linha" />
    <div id="leftsideoptions">
      <a class="opt" href="#">Sobre</a>
      <a class="opt" href="#">Preço</a>
      <a class="opt" href="#">Contato</a>
    </div>
  </div>
  <div id="rightside">
    {% if request.user.is_authenticated %}
    <a class="opt signup" href="{% url 'usuarios:plataforma' %}">Plataforma</a>
    {% else %}
    <a class="opt large" href="{% url 'usuarios:login' %}">Log in</a>
    <a class="opt signup" href="{% url 'usuarios:signup' %}">Cadastro</a>
    {% endif %}
  </div>
</div>

<div id="starter-content">
  <div id="slogan">
    <div id="insignia">
      <span><strong>#1 Top </strong>Plataforma de Ensino Online</span>
      <img id="insigina-icon" src="{% static 'home/verified.svg' %}" alt="" />
    </div>
    <h1 id="slogan-main">Eleve seu estudo.</h1>
    <p id="slogan-secondary">
      Aprimore seus conhecimentos de qualquer lugar, do seu jeito, e observe seu
      progresso se desdobrar diante de você com a
      <img id="logo" src="{% static 'home/logoinline.png' %}" alt="Logo" />
    </p>
  </div>
  <img
    id="homeimg"
    src="{% static 'home/leftimage.svg' %}"
    alt="Garoto segurando tablet"
  />
</div>

<div class="feature">
  <img
    src="{% static 'home/relatorio.svg'%}"
    alt="Imagem de computador com graficos"
  />
  <div class="feature-text-container">
    <h1 class="feature-title">Relatórios instantâneos</h1>
    <p class="feature-text">
      Gráficos e Rankings para você acompanhar seu desempenho nos conteúdos
      específicos para direcionar o seu foco no necessário.
    </p>
  </div>
</div>

<div class="feature reversed">
  <img src="{% static 'home/database.svg' %}" alt="Banco de dados icone" />
  <div class="feature-text-container">
    <h1 class="feature-title">Banco de dados completo</h1>
    <p class="feature-text">
      Nossa plataforma conta com todas as questões do Enem desde o ano de 1998.
      Possibilitando que você realize simulados realistas baseados nos contéudos
      mais presentes no Enem.
    </p>
  </div>
</div>

<div class="feature last">
  <img src="{% static 'home/ia.svg' %}" alt="Icone inteligencia artificial" />
  <div class="feature-text-container">
    <h1 class="feature-title">Inteligência Artificial integrada</h1>
    <p class="feature-text">
      Nós desenvolvemos um modelo avançado de Inteligência Artificial (IA)
      projetado para efetuar a correção de redações. Este modelo se destaca pela
      sua alta precisão de correção de erros e pela capacidade de sugerir
      alterações no texto que potencializam a obtenção de uma nota mais elevada.
      Neste modelo, foram adotados os critérios de avaliação estabelecidos pelo
      Instituto Nacional de Estudos e Pesquisas Educacionais Anísio Teixeira
      (INEP), assegurando assim uma correlação direta com os padrões nacionais
      de avaliação.
    </p>
  </div>
  </div>
{% endblock %}